<a href="https://colab.research.google.com/github/Shubham00722Shah/test_repo_aug/blob/main/Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
  l1=[1,2,3,4,5]

#required ouput l1=[2,4,6,8,10]

In [1]:
import numpy as np

In [20]:
l1=np.array(l1)
print(list(l1*2))

[2, 4, 6, 8, 10]


#Elementwise multiplication of list

In [6]:
L1=[1,2,3,4]
L2=[5,6,7,8]

In [7]:
L1=np.array(L1)
L2=np.array(L2)

In [19]:
print(list(L1*L2))

[5, 12, 21, 32]


#Element wise addition of list

In [13]:
L3=[1,2,3,4,5]
L4=[6,7,8,9,10]

In [18]:
L3=np.array(L3)
L4=np.array(L4)

print(list(L3+L4))

[7, 9, 11, 13, 15]


# Filtering only even numbers

In [17]:
L5=[1,2,3,4,5,6,7,8,9,10]
L5=np.array(L5)
print(list(L5[L5%2==0]))

[2, 4, 6, 8, 10]


#Finding the Minimum and Maximum Values of the List

In [21]:
L6=[3,7,1,9,5]
L6=np.array(L6)
print(L6.max())
print(L6.min())

9
1


#Reshaping the List

In [22]:
L7=[1,2,3,4,5,6,7,8,9]
L7=np.array(L7)
print(L7.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#Summation of Matrix Element

In [23]:
L8=[[1,2,3],[4,5,6]]
L8=np.array(L8)
print(L8.sum())

21


# Generate an output list with elements present at respective indices

In [24]:
num = [10, 20, 30, 40, 50]
i= [2, 0, 3, 1, 1]
num=np.array(num)
i=np.array(i)
print(list(num[i]))

[30, 10, 40, 20, 20]


#Matrix Multiplication

In [26]:
l8 = [[1, 2], [3, 4]]
l9 = [[5, 6], [7, 8]]
l8=np.array(l8)
l9=np.array(l9)
print(l8)
print(l9)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [2]:
import numpy as np

In [2]:
mat=np.array([[1,2,3,4],[4,5,6,7]])

In [4]:
arr=np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [5]:
arr.ndim,arr.shape

(1, (16,))

In [6]:
mat=arr.reshape(4,4)
mat

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [7]:
mat.ndim,mat.shape

(2, (4, 4))

In [8]:
arr1=mat
print(arr1.T)


[[ 0  4  8 12]
 [ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]]


In [9]:
m1=np.arange(1,10).reshape(3,3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
m1[0]

array([1, 2, 3])

In [14]:
m1[0][1]

2

#This is only works in numpy

In [17]:
m1[0,1] # is same as m1[0][1]

2

In [18]:
m1[1,2] # is same as m1[1][2]

6

In [19]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
m1[[1,2]]

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
index=[[1,2],[1,2]]
m1[index]

array([[[4, 5, 6],
        [7, 8, 9]],

       [[4, 5, 6],
        [7, 8, 9]]])

In [23]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
m1[:,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
m1[:,1]

array([2, 5, 8])

In [26]:
m1[1,:]

array([4, 5, 6])

In [27]:
m1[:,1]=-1
m1

array([[ 1, -1,  3],
       [ 4, -1,  6],
       [ 7, -1,  9]])

In [5]:
m2=np.arange(1,13).reshape(3,4)
m2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [6]:
m2<6

array([[ True,  True,  True,  True],
       [ True, False, False, False],
       [False, False, False, False]])

In [7]:
m2[m2<6]

array([1, 2, 3, 4, 5])

In [8]:
ar=np.array([1,2,3,4,5,6,7,8])
ar%2==0

array([False,  True, False,  True, False,  True, False,  True])

In [10]:
mask=ar%2==0
mask

array([False,  True, False,  True, False,  True, False,  True])

In [11]:
mask=ar[ar%2==0]
mask

array([2, 4, 6, 8])

In [12]:
ar[ar%2==0]=-1
ar

array([ 1, -1,  3, -1,  5, -1,  7, -1])

#Agrregate Function

In [13]:
a1=np.array([1,2,3,4,5,6,7,8,9])
m1=np.arange(1,13).reshape(3,4)
a1,m1

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [16]:
s1=np.sum(a1)
s2=np.sum(m1)
s1,s2

(45, 78)

In [17]:
min1=np.min(a1)
min2=np.min(m1)
min1,min2

(1, 1)

In [18]:
max1=np.max(a1)
max2=np.max(m1)
max1,max2

(9, 12)

In [19]:
mean1=np.mean(a1)
mean2=np.mean(m1)
mean1,mean2

(5.0, 6.5)

In [20]:
m1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
#mean of  each rows
np.mean(m1,axis=1)

array([ 2.5,  6.5, 10.5])

In [24]:
np.mean(m1,axis=1)[0]

2.5

In [25]:
np.mean(m1,axis=1)[1]

6.5

In [26]:
np.mean(m1,axis=1)[2]

10.5

In [22]:
#mean of each column
np.mean(m1,axis=0)

array([5., 6., 7., 8.])

In [27]:
np.mean(m1,axis=0)[0]

5.0

In [32]:
np.mean(m1[:,0])

5.0

In [30]:
np.mean(m1,axis=0)[1]

6.0

In [33]:
np.mean(m1[:,1])

6.0

In [31]:
np.mean(m1,axis=0)[2]

7.0

In [34]:
np.mean(m1[:,2])

7.0

#Logical Operations like any/all/where

In [35]:
arr=np.array([50,25,64,30,41,10])
budget=30
tr=np.any(arr<budget)
tr

True

In [36]:
arr=np.array([50,25,64,30,41,10])
budget=30
tr=np.all(arr<budget)
tr

False

#apply 10% discount on item whose price is grater than or equal to 50

In [37]:
arr=np.array([50,25,64,30,41,10])
tr=np.where(arr>=50,0.9*arr,arr)
tr

array([45. , 25. , 57.6, 30. , 41. , 10. ])

#fit.txt task

In [1]:
import numpy as np

In [10]:
data=np.loadtxt('fit.txt',dtype='str')

In [3]:
data.shape

(96, 6)

###Number of unique mood set

In [7]:
moodset=data[:,2:3]
unique_m=np.unique(moodset)
unique_m

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

###Average number of stepcount across each moodset

In [27]:
#Happy
Happy_mset=np.where(data[:,2]=='Happy',data[:,1], None) # Extracting all the stepcount values of 'Happy'
Happy_mset=Happy_mset[Happy_mset!=None].astype(np.int32) #Converting str to int and discarding 'None' value

#Neutral
Neutral_mset=np.where(data[:,2]=='Neutral',data[:,1], None)
Neutral_mset=Neutral_mset[Neutral_mset!=None].astype(np.int32)

#Sad
Sad_mset=np.where(data[:,2]=='Sad',data[:,1], None)
Sad_mset=Sad_mset[Sad_mset!=None].astype(np.int32)

H=round(np.mean(Happy_mset),2)
N=round(np.mean(Neutral_mset),2)
S=round(np.mean(Sad_mset),2)

H,N,S

(3392.72, 3153.78, 2103.07)

#Date on which user walked the most i.e max

In [38]:
step_count=list(data[:,1].astype(np.int32))
max_stepcount=max(step_count)
i=step_count.index(max_stepcount)
data[i,0]

'14-12-2017'